version : "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: app
    image: app
    tty: true
    restart: unless-stopped
    logging:
      driver: json-file
    volumes:
      - ./:/app
    environment:
      HOST: localhost
      DB_PASSWORD: mysecretpassword
      DB_USERNAME: postgres
      DB: postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
